map_change_node:
  ros__parameters: 
    map_path: "/home/shugo/ros2_ws/src/map_changer/csv/maps/241002.csv"
    pose_path: "/home/shugo/ros2_ws/src/map_changer/csv/poses/241002.csv"
    start_number: 2
    
